set_max_players + wip set_username
z-korp/zconqueror-contracts pull request #15
Opened 2024-02-05 19:11 UTC by caillef

2024-02-10 14:44 UTC, Cheelax commented on src/systems/host.cairo
> -        ) -> u32 {
Est ce qu'ici on pourrait envisager de laisser le player_name en optionel?
ça nous permettrait pour l'instant de laisser le player_name à entrer dans le front tant qu'on a pas terminé de le gérer différement

2024-02-10 14:44 UTC, Cheelax commented on src/systems/host.cairo
> +        fn join(self: @ContractState, world: IWorldDispatcher, game_id: u32) {
meme question pour le player name optionel

2024-02-11 15:51 UTC, Bal7hazar requested changes

2024-02-11 15:51 UTC, Bal7hazar commented on src/systems/host.cairo
> +            loop {
This loop is done 3 times at the end:
- In the store
- In this function
- In the`Game::set_max_players` function

This is very inefficient and players will pay this in fee.
We can either:
- Remove the `set_max_players` and consider only having a hard coded max player with the ability to start an unfilled game
- Skip this loop and just provide a Span<Player> to `Game::set_max_players`

2024-02-12 10:38 UTC, merged